# Generated by Django 5.0.6 on 2024-06-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('free_consultation', models.BooleanField()),
                ('back_up_money', models.BigIntegerField()),
                ('couching', models.BooleanField()),
                ('consultation_about_sport', models.BooleanField()),
                ('free_week_for_family', models.BooleanField()),
                ('sort', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name': 'Пропозиція',
                'verbose_name_plural': 'Наші пропозиції',
                'ordering': ['sort'],
            },
        ),
    ]
