# Generated by Django 5.0.6 on 2024-06-07 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('eating_plan', models.BooleanField()),
                ('free_consultation', models.BooleanField()),
                ('back_up_money', models.BooleanField()),
                ('couching', models.BooleanField()),
                ('consultation_about_sport', models.BooleanField()),
                ('free_week_for_family', models.BooleanField()),
                ('sort', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=255)),
                ('is_visible', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Пропозиція',
                'verbose_name_plural': 'Наші пропозиції',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='DietitianClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='Клієнти', to=settings.AUTH_USER_MODEL)),
                ('dietitian', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Дієтологи', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клієнт дієтолога',
                'verbose_name_plural': 'Клієнти дієтологів',
            },
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.discountmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
