# Generated by Django 5.0.6 on 2024-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='eating_plan',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
