# Generated by Django 5.0.6 on 2024-06-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_offermodel_back_up_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='is_visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
