# Generated by Django 5.0.6 on 2024-06-03 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_dietitianclient_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietitianclient',
            name='client',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='Клієнти', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dietitianclient',
            name='dietitian',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Дієтологи', to=settings.AUTH_USER_MODEL),
        ),
    ]
