# Generated by Django 5.0.6 on 2024-06-02 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallBackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введіть ваш номер у форматі: +380xxxxxxx', regex='\\+?(380)?0?d{7}$')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('count', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заявка на дзвінок',
                'verbose_name_plural': 'Заявки на дзвінок',
                'ordering': ['-date_created'],
            },
        ),
    ]
