# Generated by Django 5.0.6 on 2024-06-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackmodel',
            name='count',
        ),
    ]
