# Generated by Django 5.0.6 on 2024-06-03 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_callbackmodel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackmodel',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введіть ваш номер у форматі: +380xxxxxxx', regex='^\\+?380\\d{9}$|^0\\d{9}$')]),
        ),
    ]
